FROM apache/airflow:2.9.0

#/ Para instalar una libreria de python se usa el misno comando que se usaria en un entorno virtual pero con la parabra RUN
#/ El --user se le pone para que no de problemas de permisos al instalar el paquete
RUN pip install pandas --user 
