version: "3.7"

  #/  Lo primero que vemos son algunas variables, es una caracteristica muy vacana y es que puede cojer la configuración desde las variables del sistema operativo 
x-airflow-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor 
  AIRFLOW__CORE__LOAD_EXAMPLES: "False" 
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow 
  AIRFLOW__CORE__FERNET_KEY: FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM= 
  AIRFLOW__DAG_DEFAULT_VIEW: graph 
  #/ Por aca definimos la variable
  AIRFLOW_VAR_EMAIL_PRUEBA: jesus@prueba2.com



services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
  init:
    #image: apache/airflow:1.10.10
    #/ Esto lo que indica es que tiene que buscar un archivo Dokerfile al mismo nivel de el docker compose
    build: .
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: >
      -c "airflow list_users || (airflow initdb
      && airflow create_user --role Admin --username airflow --password airflow -e airflow@airflow.com -f airflow -l airflow)"
    restart: on-failure

  #! en el webserver y en el scheduler poner el volumen
  webserver:
    #image: apache/airflow:1.10.10
    build: .
    ports:
      - 9090:8080 
    environment:
      <<: *airflow-environment
    depends_on:
      - init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      #/ Desde aca creamos un volumen para importar las variables
      - ./variables.json:/otp/airflow/variables.json
    entrypoint: /bin/bash
    #! aca ponemos el comando para importar las variables en el scheduler tambien
    command: -c "airflow variables -i /otp/airflow/variables.json && airflow webserver"
    restart: always
  
  scheduler:
    build: .
    #image: apache/airflow:1.10.10
    environment:
      <<: *airflow-environment
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      #/ Desde aca creamos un volumen para importar las variables
      - ./variables.json:/otp/airflow/variables.json
    entrypoint: /bin/bash
    #/ aca cambios
    command: -c "airflow variables -i /otp/airflow/variables.json && airflow scheduler"
    restart: always